export const SET_DOMAIN_SLUG = "SET_DOMAIN_SLUG"
export const SET_DOMAIN_SLUG_lOCALLY = "SET_DOMAIN_SLUG_LOCALLY"

export const  SET_STATE_PENDING = "SET_STATE_PENDING"
export const  SET_STATE_COMPLETED = "SET_STATE_COMPLETED"